spring:
  main:
    web-application-type: none
interval: 60000
opc-url: opc.tcp://10.73.30.224:48400
username: admin
password: admin
push-url: http://localhost:6666/gas/add
push-multi-url: http://localhost:6666/gas/multi/add
region: huabei
points:
  list:
    - { point: 1459, pname: 苏桥_霸州分输站\流量计1参数\BKSSLL ,unit: Nm3/h ,tableName: sq_flow1_BKSSLL }
    - { point: 1457, pname: 苏桥_霸州分输站\流量计1参数\GDYL ,unit: MPa ,tableName: sq_flow1_GDYL }
    - { point: 1509,  pname: 苏桥_霸州分输站\流量计2参数\BKSSLL ,unit: Nm3/h ,tableName: sq_flow2_BKSSLL }
    - { point: 1507,  pname: 苏桥_霸州分输站\流量计2参数\GDYL ,unit: MPa,tableName: sq_flow2_GDYL }
    - { point: 1559,  pname: 苏桥_霸州分输站\流量计3参数\BKSSLL ,unit: Nm3/h ,tableName: sq_flow3_BKSSLL }
    - { point: 1557,  pname: 苏桥_霸州分输站\流量计3参数\GDYL ,unit: MPa,tableName: sq_flow3_GDYL }
    - { point: 1609,  pname: 苏桥_霸州分输站\流量计4参数\BKSSLL ,unit: Nm3/h,tableName: sq_flow4_BKSSLL }
    - { point: 1607,  pname: 苏桥_霸州分输站\流量计4参数\GDYL ,unit: MPa,tableName: sq_flow4_GDYL }
