spring:
  main:
    web-application-type: none
interval: 60000
opc-url: opc.tcp://10.73.30.224:48400
username: admin
password: admin
push-url: http://localhost:6666/gas/add
push-multi-url: http://localhost:6666/gas/multi/add
region: xinan
points:
  list:
    - { point: 霸州分输站\流量计1参数\BKSSLL, unit: Nm3/h ,tableName: flow1_BKSSLL }
    - { point: 霸州分输站\流量计1参数\GDYL, unit: MPa ,tableName: flow1_GDYL }
    - { point: 霸州分输站\流量计2参数\BKSSLL, unit: Nm3/h ,tableName: flow2_BKSSLL }
    - { point: 霸州分输站\流量计2参数\GDYL, unit: MPa,tableName: flow2_GDYL }
    - { point: 霸州分输站\流量计3参数\BKSSLL, unit: Nm3/h ,tableName: flow3_BKSSLL }
    - { point: 霸州分输站\流量计3参数\GDYL, unit: MPa,tableName: flow3_GDYL }
    - { point: 霸州分输站\流量计4参数\BKSSLL, unit: Nm3/h,tableName: flow4_BKSSLL }
    - { point: 霸州分输站\流量计4参数\GDYL, unit: MPa,tableName: flow4_GDYL }
